export class Constants {
  public static CRAFTTYPE = {
    0: "None",
    1: "X-wing",
    2: "Y-wing",
    3: "A-wing",
    4: "B-wing",
    5: "TIE Fighter",
    6: "TIE Interceptor",
    7: "TIE Bomber",
    8: "TIE Advanced",
    9: "TIE Defender",
    10: "Patch Slot 10",
    11: "Patch Slot 11",
    12: "Missile Boat",
    13: "T-wing",
    14: "Z-95 Headhunter",
    15: "R-41 Starchaser",
    16: "Assault Gunboat",
    17: "Shuttle",
    18: "Escort Shuttle",
    19: "System Patrol Craft",
    20: "Scout Craft",
    21: "Stormtrooper Transport",
    22: "Assault Transport",
    23: "Escort Transport",
    24: "Tug",
    25: "Combat Utility Vehicle",
    26: "Container A",
    27: "Container B",
    28: "Container C",
    29: "Container D",
    30: "Heavy Lifter",
    31: "Unused",
    32: "Bulk Freighter",
    33: "Cargo Ferry",
    34: "Modular Conveyor",
    35: "Container Transport",
    36: "Unused",
    37: "Murrian Transport",
    38: "Corellian Transport",
    39: "Unused",
    40: "Corellian Corvette",
    41: "Modified Corvette",
    42: "Nebulon-B Frigate",
    43: "Modified Frigate",
    44: "C-3 Passenger Liner",
    45: "Carrack Cruiser",
    46: "Strike Cruiser",
    47: "Escort Carrier",
    48: "Dreadnaught",
    49: "Mon Calamari Cruiser",
    50: "Light Mon Calamari Cruiser",
    51: "Interdictor Cruiser",
    52: "Victory-class Star Destroyer",
    53: "Imperator-class Star Destroyer",
    54: "Unused",
    55: "Container E",
    56: "Container F",
    57: "Container G",
    58: "Container H",
    59: "Container I",
    60: "Platform A",
    61: "Platform B",
    62: "Platform C",
    63: "Platform D",
    64: "Platform E",
    65: "Platform F",
    66: "Asteroid R&D Station",
    67: "Asteroid Laser Battery",
    68: "Asteroid Warhead Battery",
    69: "X/7 Factory",
    70: "Satellite 1",
    71: "Satellite 2",
    72: "Unused",
    73: "Unused",
    74: "Unused",
    75: "Mine A",
    76: "Mine B",
    77: "Mine C",
    78: "Unused",
    79: "Unused",
    80: "Probe A",
    81: "Probe B",
    82: "Unused",
    83: "Nav Buoy A",
    84: "Nav Buoy B",
    85: "Unused",
    86: "Asteroid Field",
    87: "Planet",
  };

  public static CRAFTABBR = {
    0: "None",
    1: "X-W",
    2: "Y-W",
    3: "A-W",
    4: "B-W",
    5: "T/F",
    6: "T/I",
    7: "T/B",
    8: "T/A",
    9: "T/D",
    10: "PATCH10",
    11: "PATCH11",
    12: "MIS",
    13: "T-W",
    14: "Z-95",
    15: "R-41",
    16: "GUN",
    17: "SHU",
    18: "E/S",
    19: "SPC",
    20: "SCT",
    21: "TRN",
    22: "ATR",
    23: "ETR",
    24: "TUG",
    25: "CUV",
    26: "CN/A",
    27: "CN/B",
    28: "CN/C",
    29: "CN/D",
    30: "HLF",
    31: "GPLT",
    32: "FRT",
    33: "CARG",
    34: "CNVYR",
    35: "CTRNS",
    36: "MDTRN",
    37: "MUTR",
    38: "CORT",
    39: "M/SC",
    40: "CRV",
    41: "M/CRV",
    42: "FRG",
    43: "M/FRG",
    44: "LINER",
    45: "CRCK",
    46: "STRCK",
    47: "ESC",
    48: "DREAD",
    49: "CRS",
    50: "CRL",
    51: "INT",
    52: "VSD",
    53: "ISD",
    54: "SSD",
    55: "CN/E",
    56: "CN/F",
    57: "CN/G",
    58: "CN/H",
    59: "CN/I",
    60: "PLT/1",
    61: "PLT/2",
    62: "PLT/3",
    63: "PLT/4",
    64: "PLT/5",
    65: "PLT/6",
    66: "R&D FC",
    67: "LAS BAT",
    68: "W LNCHR",
    69: "FAC/1",
    70: "SAT 1",
    71: "SAT/2",
    72: "UNK",
    73: "UNK",
    74: "UNK",
    75: "MINE 1",
    76: "MINE B",
    77: "MINE C",
    78: "UNK",
    79: "UNK",
    80: "PROBE A",
    81: "PROBE B",
    82: "UNK",
    83: "NAV 1",
    84: "NAV 2",
    85: "Asteroid",
    86: "Asteroid",
    87: "Planet",
  };

  public static STATUS = {
    0: "None",
    1: "2X Warheads",
    2: "1/2 Warheads",
    3: "Disabled",
    4: "1/2 Shields",
    5: "No Lasers",
    6: "No Hyperdrive",
    7: "Shields 0%, charging",
    8: "Shields added or 200%",
    9: "Hyperdrive added",
    20: "Invincible",
  };

  public static WARHEAD = {
    0: "None",
    1: "Heavy Rocket",
    2: "Space Bomb",
    3: "Concussion Missile",
    4: "Torpedo",
    5: "Advanced Concussion Missile",
    6: "Advanced Torpedo",
    7: "Mag Pulse Torpedo",
  };

  public static BEAM = {
    0: "None",
    1: "Tractor Beam",
    2: "Jamming Beam",
  };

  public static GROUPAI = {
    0: "Rookie (None)",
    1: "Novice",
    2: "Veteran",
    3: "Officer",
    4: "Ace",
    5: "Top Ace (Invincible)",
  };

  public static MARKINGS = {
    0: "Red (TIE - None)",
    1: "Gold (TIE - Red)",
    2: "Blue (TIE - Gold)",
    3: "Green (TIE - Blue)",
  };

  public static FORMATION = {
    0: "Vic",
    1: "Finger Four",
    2: "Line Astern",
    3: "Line Abreast",
    4: "Echelon Right",
    5: "Echelon Left",
    6: "Double Astern",
    7: "Diamond",
    8: "Stack",
    9: "High X",
    10: "Vic Abreast",
    11: "High Vic",
    12: "Reverse High Vic",
  };

  public static ARRIVALDIFFICULTY = {
    0: "All",
    1: "Easy",
    2: "Medium",
    3: "Hard",
    4: "Medium, Hard",
    5: "Easy, Medium",
  };

  public static CONDITION = {
    0: "Always (true)",
    1: "Created",
    2: "Destroyed",
    3: "Attacked",
    4: "Captured",
    5: "Inspected",
    6: "Boarded",
    7: "Docked",
    8: "Disabled",
    9: "Survived (exist)",
    10: "None (false)",
    11: "Unknown (---)",
    12: "Completed mission",
    13: "Completed Primary Goals",
    14: "Failed Primary Goals",
    15: "Completed Secondary Goals",
    16: "Failed Secondary Goals",
    17: "Completed Bonus Goals",
    18: "Failed Bonus Goals",
    19: "Dropped off",
    20: "Reinforced",
    21: "0% Shields",
    22: "50% Hull",
    23: "Out of Warheads",
    24: "Unknown (arrive?)",
  };

  public static VARIABLETYPE = {
    0: "None",
    1: "Flight Group",
    2: "CraftType (enum)",
    3: "CraftCategory (enum)",
    4: "ObjectCategory (enum)",
    5: "IFF",
    6: "Order (enum)",
    7: "CraftWhen (enum)",
    8: "Global Group",
    9: "Misc (enum)",
    10: "Unknown",
  };

  public static CRAFTCATEGORY = {
    0: "Starfighters",
    1: "Transports",
    2: "Freighters/Containers",
    3: "Starships",
    4: "Utility Craft",
    5: "Platforms/Facilities",
    6: "Mines",
  };

  public static OBJECTCATEGORY = {
    0: "Craft",
    1: "Weapons",
    2: "Space Objects",
  };

  public static TRIGGERAMOUNT = {
    0: "100%",
    1: "75%",
    2: "50%",
    3: "25%",
    4: "At least one",
    5: "All but one",
    6: "Special craft",
    7: "All non-special craft",
    8: "All non-player craft",
    9: "Player's craft",
    10: "100% of first wave",
    11: "75% of first wave",
    12: "50% of first wave",
    13: "25% of first wave",
    14: "At least one of first wave",
    15: "All but one of first wave",
  };

  public static GOALAMOUNT = {
    0: "100%",
    1: "50%",
    2: "At least one",
    3: "All but one",
    4: "Special craft",
  };

  public static ABORTTRIGGER = {
    0: "None",
    1: "0% Shields",
    2: "Systems 75% (fighters and transports only)",
    3: "Out of warheads",
    4: "50% Hull",
    5: "Attacked",
  };

  public static ORDER = {
    0: "Hold Station",
    1: "Go Home",
    2: "Circle",
    // Var1 Docking Time (seconds x 5)
    3: "Circle and Evade",
    4: "Rendezvous",
    5: "Disabled",
    6: "Await Boarding",
    7: "Attack",
    8: "Attack Escorts",
    9: "Protect",
    10: "Escort",
    11: "Disable",
    12: "Board and Give Cargo",
    // Var2 Number of Dockings
    13: "Board and Take Cargo",
    14: "Board and Exchange Cargo",
    15: "Board and Capture Cargo",
    16: "Board and Destroy Cargo",
    17: "Pick up",
    18: "Drop off",
    19: "Wait",
    20: "SS Wait",
    21: "SS Patrol Loop",
    22: "SS Await Return",
    23: "SS Launch",
    24: "SS Protect",
    25: "SS Wait and Protect",
    26: "SS Patrol and Attack",
    27: "SS Patrol and Disable",
    28: "SS Hold Steady",
    29: "SS Go Home",
    30: "SS Wait",
    31: "SS Board",
    32: "Board to Repair",
    33: "Hold Station",
    34: "Hold Steady",
    35: "SS Hold Station",
    36: "SS Kamikaze?",
    37: "SS Kamikaze?",
    38: "SS Disabled",
    39: "SS Disabled",
  };

  public static CRAFTWHEN = {
    1: "Boarding",
    2: "Boarded",
    3: "Defence",
    4: "Disabled",
    7: "Special craft",
    8: "Non-special craft",
    9: "Player's craft",
    10: "Non-player's craft",
  };

  public static MISC = {
    0: "Rookie craft",
    1: "Novice craft",
    2: "Officer craft",
    3: "Veteran craft",
    4: "Ace craft",
    5: "Top Ace craft",
    6: "Stationary craft",
    7: "Craft returning to base",
    8: "Non-evading craft",
    9: "Craft in formation",
    10: "Rendezvousing craft",
    11: "Disabled craft",
    12: "Craft awaiting boarding",
    13: "Attacking craft",
    14: "Craft atatcking escorts",
    15: "Protecting craft",
    16: "Escorting craft",
    17: "Disabling craft",
    18: "Delivering craft",
    19: "Siezing craft",
    20: "Exchanging craft",
    21: "Capturing craft",
    22: "Craft destroying cargo",
    23: "Picked up craft",
    24: "Dropped off craft",
    25: "Waiting fighters",
    26: "Waiting starships",
    27: "Patrolling starships",
    28: "SS awaiting returns",
    29: "SS waiting to launch",
    30: "SS waiting to be boarded",
    31: "SS witing for boarding craft to appear",
    32: "SS attacking",
    33: "SS disabling",
    34: "SS disabling?",
    35: "SS flying home",
    36: "Rebels",
    37: "Imperials",
    39: "Spacecraft",
    40: "Weapons",
    41: "Space objects",
    46: "Fighters",
    47: "Transports",
    48: "Freighters",
    49: "Utility craft",
    50: "Startships",
    51: "Platforms",
    54: "Mines",
  };

  public static EVENTTYPE = {
    3: "Page Break",
    4: "Title Text",
    // Var1 Tag#
    5: "Caption Text",
    6: "Move Map",
    // Var2 TextTagColor (enum)
    7: "Zoom Map",
    8: "Clear FG Tags",
    9: "FG Tag 1",
    10: "FG Tag 2",
    11: "FG Tag 3",
    12: "FG Tag 4",
    13: "FG Tag 5",
    14: "FG Tag 6",
    15: "FG Tag 7",
    16: "FG Tag 8",
    17: "Clear Text Tags",
    18: "Text Tag 1",
    // Var3 X
    // Var4 Y
    19: "Text Tag 2",
    20: "Text Tag 3",
    21: "Text Tag 4",
    22: "Text Tag 5",
    23: "Text Tag 6",
    24: "Text Tag 7",
    25: "Text Tag 8",
    34: "End Briefing",
  };

  public static TEXTTAGCOLOR = {
    0: "Green",
    1: "Red",
    2: "Purple",
    3: "Blue",
    4: "Red",
    5: "Light Red",
    6: "Gray",
    7: "White",
  };

  public static BRIEFINGOFFICERS = {
    1: "Both officers",
    2: "Flight Officer",
    3: "Secret Order",
  };

  public static QUESTIONTYPE = {
    0: "None",
    1: "Primary Goals",
    2: "Secondary Goals",
  };

  public static QUESTIONCONDITION = {
    0: "None",
    4: "Successful",
    5: "Failed",
  };

  public static MESSAGECOLOR = {
    0: "Red",
    1: "Green",
    2: "Blue",
    3: "Purple",
  };

  public static IFFCOLOR = {
    0: "Green",
    1: "Red",
    2: "Purple",
    3: "Blue",
  };

}


export enum CraftType {
  None = 0,
  Xwing = 1,
  Ywing = 2,
  Awing = 3,
  Bwing = 4,
  TIEFighter = 5,
  TIEInterceptor = 6,
  TIEBomber = 7,
  TIEAdvanced = 8,
  TIEDefender = 9,
  PatchSlot10 = 10,
  PatchSlot11 = 11,
  MissileBoat = 12,
  Twing = 13,
  Z95Headhunter = 14,
  R41Starchaser = 15,
  AssaultGunboat = 16,
  Shuttle = 17,
  EscortShuttle = 18,
  SystemPatrolCraft = 19,
  ScoutCraft = 20,
  StormtrooperTransport = 21,
  AssaultTransport = 22,
  EscortTransport = 23,
  Tug = 24,
  CombatUtilityVehicle = 25,
  ContainerA = 26,
  ContainerB = 27,
  ContainerC = 28,
  ContainerD = 29,
  HeavyLifter = 30,
  Unused = 31,
  BulkFreighter = 32,
  CargoFerry = 33,
  ModularConveyor = 34,
  ContainerTransport = 35,
  // Unused = 36,
  MurrianTransport = 37,
  CorellianTransport = 38,
  // Unused = 39,
  CorellianCorvette = 40,
  ModifiedCorvette = 41,
  NebulonBFrigate = 42,
  ModifiedFrigate = 43,
  C3PassengerLiner = 44,
  CarrackCruiser = 45,
  StrikeCruiser = 46,
  EscortCarrier = 47,
  Dreadnaught = 48,
  MonCalamariCruiser = 49,
  LightMonCalamariCruiser = 50,
  InterdictorCruiser = 51,
  VictoryclassStarDestroyer = 52,
  ImperatorclassStarDestroyer = 53,
  // Unused = 54,
  ContainerE = 55,
  ContainerF = 56,
  ContainerG = 57,
  ContainerH = 58,
  ContainerI = 59,
  PlatformA = 60,
  PlatformB = 61,
  PlatformC = 62,
  PlatformD = 63,
  PlatformE = 64,
  PlatformF = 65,
  AsteroidRnDStation = 66,
  AsteroidLaserBattery = 67,
  AsteroidWarheadBattery = 68,
  X7Factory = 69,
  Satellite1 = 70,
  Satellite2 = 71,
  // Unused = 72,
  // Unused = 73,
  // Unused = 74,
  MineA = 75,
  MineB = 76,
  MineC = 77,
  // Unused = 78,
  // Unused = 79,
  ProbeA = 80,
  ProbeB = 81,
  // Unused = 82,
  NavBuoyA = 83,
  NavBuoyB = 84,
  // Unused = 85,
  AsteroidField = 86,
  Planet = 87,
}

export enum CraftAbbr {
  None = 0,
  XW = 1,
  YW = 2,
  AW = 3,
  BW = 4,
  TF = 5,
  TI = 6,
  TB = 7,
  TA = 8,
  TD = 9,
  PATCH10 = 10,
  PATCH11 = 11,
  MIS = 12,
  TW = 13,
  Z95 = 14,
  R41 = 15,
  GUN = 16,
  SHU = 17,
  ES = 18,
  SPC = 19,
  SCT = 20,
  TRN = 21,
  ATR = 22,
  ETR = 23,
  TUG = 24,
  CUV = 25,
  CNA = 26,
  CNB = 27,
  CNC = 28,
  CND = 29,
  HLF = 30,
  GPLT = 31,
  FRT = 32,
  CARG = 33,
  CNVYR = 34,
  CTRNS = 35,
  MDTRN = 36,
  MUTR = 37,
  CORT = 38,
  MSC = 39,
  CRV = 40,
  MCRV = 41,
  FRG = 42,
  MFRG = 43,
  LINER = 44,
  CRCK = 45,
  STRCK = 46,
  ESC = 47,
  DREAD = 48,
  CRS = 49,
  CRL = 50,
  INT = 51,
  VSD = 52,
  ISD = 53,
  SSD = 54,
  CNE = 55,
  CNF = 56,
  CNG = 57,
  CNH = 58,
  CNI = 59,
  PLT1 = 60,
  PLT2 = 61,
  PLT3 = 62,
  PLT4 = 63,
  PLT5 = 64,
  PLT6 = 65,
  RnDFC = 66,
  LASBAT = 67,
  WLNCHR = 68,
  FAC1 = 69,
  SAT1 = 70,
  SAT2 = 71,
  UNK = 72,
  // UNK = 73,
  // UNK = 74,
  MINE1 = 75,
  MINEB = 76,
  MINEC = 77,
  // UNK = 78,
  // UNK = 79,
  PROBEA = 80,
  PROBEB = 81,
  // UNK = 82,
  NAV1 = 83,
  NAV2 = 84,
  Asteroid = 85,
  // Asteroid = 86,
  Planet = 87,
}

export enum Status {
  None = 0,
  n2XWarheads = 1,
  n12Warheads = 2,
  Disabled = 3,
  n12Shields = 4,
  NoLasers = 5,
  NoHyperdrive = 6,
  Shields0Percentcharging = 7,
  Shieldsaddedor200Percent = 8,
  Hyperdriveadded = 9,
  Invincible = 20,
}

export enum Warhead {
  None = 0,
  HeavyRocket = 1,
  SpaceBomb = 2,
  ConcussionMissile = 3,
  Torpedo = 4,
  AdvancedConcussionMissile = 5,
  AdvancedTorpedo = 6,
  MagPulseTorpedo = 7,
}

export enum Beam {
  None = 0,
  TractorBeam = 1,
  JammingBeam = 2,
}

export enum GroupAI {
  RookieNone = 0,
  Novice = 1,
  Veteran = 2,
  Officer = 3,
  Ace = 4,
  TopAceInvincible = 5,
}

export enum Markings {
  RedTIENone = 0,
  GoldTIERed = 1,
  BlueTIEGold = 2,
  GreenTIEBlue = 3,
}

export enum Formation {
  Vic = 0,
  FingerFour = 1,
  LineAstern = 2,
  LineAbreast = 3,
  EchelonRight = 4,
  EchelonLeft = 5,
  DoubleAstern = 6,
  Diamond = 7,
  Stack = 8,
  HighX = 9,
  VicAbreast = 10,
  HighVic = 11,
  ReverseHighVic = 12,
}

export enum ArrivalDifficulty {
  All = 0,
  Easy = 1,
  Medium = 2,
  Hard = 3,
  MediumHard = 4,
  EasyMedium = 5,
}

export enum Condition {
  Alwaystrue = 0,
  Created = 1,
  Destroyed = 2,
  Attacked = 3,
  Captured = 4,
  Inspected = 5,
  Boarded = 6,
  Docked = 7,
  Disabled = 8,
  Survivedexist = 9,
  Nonefalse = 10,
  Unknown = 11,
  Completedmission = 12,
  CompletedPrimaryGoals = 13,
  FailedPrimaryGoals = 14,
  CompletedSecondaryGoals = 15,
  FailedSecondaryGoals = 16,
  CompletedBonusGoals = 17,
  FailedBonusGoals = 18,
  Droppedoff = 19,
  Reinforced = 20,
  n0PercentShields = 21,
  n50PercentHull = 22,
  OutofWarheads = 23,
  Unknownarrive = 24,
}

export enum VariableType {
  None = 0,
  FlightGroup = 1,
  CraftTypeenum = 2,
  CraftCategoryenum = 3,
  ObjectCategoryenum = 4,
  IFF = 5,
  Orderenum = 6,
  CraftWhenenum = 7,
  GlobalGroup = 8,
  Miscenum = 9,
  Unknown = 10,
}

export enum CraftCategory {
  Starfighters = 0,
  Transports = 1,
  FreightersContainers = 2,
  Starships = 3,
  UtilityCraft = 4,
  PlatformsFacilities = 5,
  Mines = 6,
}

export enum ObjectCategory {
  Craft = 0,
  Weapons = 1,
  SpaceObjects = 2,
}

export enum TriggerAmount {
  n100Percent = 0,
  n75Percent = 1,
  n50Percent = 2,
  n25Percent = 3,
  Atleastone = 4,
  Allbutone = 5,
  Specialcraft = 6,
  Allnonspecialcraft = 7,
  Allnonplayercraft = 8,
  Playerscraft = 9,
  n100Percentoffirstwave = 10,
  n75Percentoffirstwave = 11,
  n50Percentoffirstwave = 12,
  n25Percentoffirstwave = 13,
  Atleastoneoffirstwave = 14,
  Allbutoneoffirstwave = 15,
}

export enum GoalAmount {
  n100Percent = 0,
  n50Percent = 1,
  Atleastone = 2,
  Allbutone = 3,
  Specialcraft = 4,
}

export enum AbortTrigger {
  None = 0,
  n0PercentShields = 1,
  Systems75Percentfightersandtransportsonly = 2,
  Outofwarheads = 3,
  n50PercentHull = 4,
  Attacked = 5,
}

export enum Order {
  HoldStation = 0,
  GoHome = 1,
  Circle = 2,
  CircleandEvade = 3,
  Rendezvous = 4,
  Disabled = 5,
  AwaitBoarding = 6,
  Attack = 7,
  AttackEscorts = 8,
  Protect = 9,
  Escort = 10,
  Disable = 11,
  BoardandGiveCargo = 12,
  BoardandTakeCargo = 13,
  BoardandExchangeCargo = 14,
  BoardandCaptureCargo = 15,
  BoardandDestroyCargo = 16,
  Pickup = 17,
  Dropoff = 18,
  Wait = 19,
  SSWait = 20,
  SSPatrolLoop = 21,
  SSAwaitReturn = 22,
  SSLaunch = 23,
  SSProtect = 24,
  SSWaitandProtect = 25,
  SSPatrolandAttack = 26,
  SSPatrolandDisable = 27,
  SSHoldSteady = 28,
  SSGoHome = 29,
  // SS Wait = 30,
  SSBoard = 31,
  BoardtoRepair = 32,
  // Hold Station = 33,
  HoldSteady = 34,
  SSHoldStation = 35,
  SSKamikaze = 36,
  // SS Kamikaze? = 37,
  SSDisabled = 38,
  // SS Disabled = 39,
}

export enum CraftWhen {
  Boarding = 1,
  Boarded = 2,
  Defence = 3,
  Disabled = 4,
  Specialcraft = 7,
  Nonspecialcraft = 8,
  Playerscraft = 9,
  Nonplayerscraft = 10,
}

export enum Misc {
  Rookiecraft = 0,
  Novicecraft = 1,
  Officercraft = 2,
  Veterancraft = 3,
  Acecraft = 4,
  TopAcecraft = 5,
  Stationarycraft = 6,
  Craftreturningtobase = 7,
  Nonevadingcraft = 8,
  Craftinformation = 9,
  Rendezvousingcraft = 10,
  Disabledcraft = 11,
  Craftawaitingboarding = 12,
  Attackingcraft = 13,
  Craftatatckingescorts = 14,
  Protectingcraft = 15,
  Escortingcraft = 16,
  Disablingcraft = 17,
  Deliveringcraft = 18,
  Siezingcraft = 19,
  Exchangingcraft = 20,
  Capturingcraft = 21,
  Craftdestroyingcargo = 22,
  Pickedupcraft = 23,
  Droppedoffcraft = 24,
  Waitingfighters = 25,
  Waitingstarships = 26,
  Patrollingstarships = 27,
  SSawaitingreturns = 28,
  SSwaitingtolaunch = 29,
  SSwaitingtobeboarded = 30,
  SSwitingforboardingcrafttoappear = 31,
  SSattacking = 32,
  SSdisabling = 33,
  // SS disabling? = 34,
  SSflyinghome = 35,
  Rebels = 36,
  Imperials = 37,
  Spacecraft = 39,
  Weapons = 40,
  Spaceobjects = 41,
  Fighters = 46,
  Transports = 47,
  Freighters = 48,
  Utilitycraft = 49,
  Startships = 50,
  Platforms = 51,
  Mines = 54,
}

export enum EventType {
  PageBreak = 3,
  TitleText = 4,
  CaptionText = 5,
  MoveMap = 6,
  ZoomMap = 7,
  ClearFGTags = 8,
  FGTag1 = 9,
  FGTag2 = 10,
  FGTag3 = 11,
  FGTag4 = 12,
  FGTag5 = 13,
  FGTag6 = 14,
  FGTag7 = 15,
  FGTag8 = 16,
  ClearTextTags = 17,
  TextTag1 = 18,
  TextTag2 = 19,
  TextTag3 = 20,
  TextTag4 = 21,
  TextTag5 = 22,
  TextTag6 = 23,
  TextTag7 = 24,
  TextTag8 = 25,
  EndBriefing = 34,
}

export enum TextTagColor {
  Green = 0,
  Red = 1,
  Purple = 2,
  Blue = 3,
  // Red = 4,
  LightRed = 5,
  Gray = 6,
  White = 7,
}

export enum BriefingOfficers {
  Bothofficers = 1,
  FlightOfficer = 2,
  SecretOrder = 3,
}

export enum QuestionType {
  None = 0,
  PrimaryGoals = 1,
  SecondaryGoals = 2,
}

export enum QuestionCondition {
  None = 0,
  Successful = 4,
  Failed = 5,
}

export enum MessageColor {
  Red = 0,
  Green = 1,
  Blue = 2,
  Purple = 3,
}

export enum IFFColor {
  Green = 0,
  Red = 1,
  Purple = 2,
  Blue = 3,
}

