<?php
namespace Pyrite\XvT;

class CraftType {
	public $ID;
	public $Name;

	public function __construct($ID){
		$this->ID = $ID;
		$this->Name = $this->getName();
		$this->Abbr = $this->getAbbr();
	}

	private function getName(){
		$names = array(
			'None',
			'X-wing',
			'Y-wing',
			'A-wing',
			'B-wing',
			'TIE Fighter',
			'TIE Interceptor',
			'TIE Bomber',
			'TIE Advanced',
			'*TIE Defender',
			'*Patch1',
			'*Patch2',
			'*Missile Boat',
			'T-wing',
			'Z-95 Headhunter',
			'R-41 Starchaser',
			'Assault Gunboat',
			'Shuttle',
			'Escort Shuttle',
			'System Patrol Craft',
			'*Scout Craft',
			'Stormtrooper Transport',
			'Assault Transport',
			'Escort Transport',
			'Tug',
			'Combat Utility Vehicle',
			'Container A',
			'Container B',
			'Container C',
			'Container D',
			'Heavy Lifter',
			'Unused',
			'Bulk Freighter',
			'Cargo Ferry',
			'Modular Conveyor',
			'*Container Transport',
			'Medium Transport',
			'Murrian Transport',
			'Corellian Transport',
			'Unused',
			'Corellian Corvette',
			'Modified Corvette',
			'Nebulon-B Frigate',
			'Modified Frigate',
			'*C-3 Passenger Liner',
			'*Carrack Cruiser',
			'Strike Cruiser',
			'Escort Carrier',
			'Dreadnaught',
			'Mon Calamari Cruiser',
			'Light Mon Calamari Cruiser',
			'Interdictor Cruiser',
			'Victory-class Star Destroyer',
			'Imperator-class Star Destroyer',
			'Executor-class Star Destroyer',
			'Container E',
			'Container F',
			'Container G',
			'Container H',
			'Container I',
			'Platform A',
			'Platform B',
			'Platform C',
			'Platform D',
			'Platform E',
			'Platform F',
			'Asteroid R&D Station',
			'Asteroid Laser Battery',
			'Asteroid Warhead Battery',
			'X/7 Factory',
			'Satellite 1',
			'Satellite 2',
			'Unused',
			'Unused',
			'Unused',
			'Mine A',
			'Mine B',
			'Mine C',
			'Gun Emplacement',
			'Unused',
			'Probe A',
			'Probe B',
			'Unused',
			'Nav Buoy A',
			'Nav Buoy B',
			'Unused',
			'Asteroid Field',
			'Planet',
			'Unused',
			'Unused',
			'Shipyard',
			'Repair Yard',
			'Modified Strike Cruiser'
		);
		return isset($names[$this->ID]) ? $names[$this->ID] : 'Unknown type ' . $this->ID;
	}

	private function getAbbr(){
		$names = array(
			'None',
			'X-W',
			'Y-W',
			'A-W',
			'B-W',
			'T/F',
			'T/I',
			'T/B',
			'T/A',
			'T/D',
			'PATCH1',
			'PATCH2',
			'M/B',
			'T-W',
			'Z-95',
			'R-41',
			'GUN',
			'SHU',
			'E/S',
			'System Patrol Craft',
			'*Scout Craft',
			'Stormtrooper Transport',
			'ATR',
			'Escort Transport',
			'Tug',
			'Combat Utility Vehicle',
			'Container A',
			'Container B',
			'Container C',
			'Container D',
			'Heavy Lifter',
			'Unused',
			'Bulk Freighter',
			'Cargo Ferry',
			'Modular Conveyor',
			'*Container Transport',
			'Medium Transport',
			'Murrian Transport',
			'CORT',
			'Unused',
			'Corellian Corvette',
			'Modified Corvette',
			'FRG',
			'Modified Frigate',
			'*C-3 Passenger Liner',
			'*Carrack Cruiser',
			'Strike Cruiser',
			'Escort Carrier',
			'Dreadnaught',
			'Mon Calamari Cruiser',
			'Light Mon Calamari Cruiser',
			'Interdictor Cruiser',
			'VSD',
			'ISD',
			'SSD',
			'Container E',
			'Container F',
			'Container G',
			'Container H',
			'Container I',
			'Platform A',
			'Platform B',
			'Platform C',
			'Platform D',
			'Platform E',
			'Platform F',
			'Asteroid R&D Station',
			'Asteroid Laser Battery',
			'Asteroid Warhead Battery',
			'X/7 Factory',
			'Satellite 1',
			'Satellite 2',
			'Unused',
			'Unused',
			'Unused',
			'Mine A',
			'Mine B',
			'Mine C',
			'Gun Emplacement',
			'Unused',
			'Probe A',
			'Probe B',
			'Unused',
			'Nav Buoy A',
			'Nav Buoy B',
			'Unused',
			'Asteroid Field',
			'Planet',
			'Unused',
			'Unused',
			'Shipyard',
			'Repair Yard',
			'Modified Strike Cruiser'
		);
		return isset($names[$this->ID]) ? $names[$this->ID] : 'Unknown type ' . $this->ID;
	}

	public function getPoints(){
		$points = array(
			0,
			600,
			400,
			800,
			800,
			400,
			600,
			600,
			1000,
			1600,
			400, //'Unused',
			400, //'Unused',
			1200,
			400,
			320,
			480,
			800,
			800,
			1600,
			2400,
			2400,
			600,
			960,
			1200,
			200,
			240,
			800,
			600,
			600,
			600,
			600,
			0, //'Unused',
			1200,
			1600,
			1200,
			1600,
			2400,
			2000,
			2000,
			0, //'Unused',
			1600,
			2000,
			4400,
			4000,
			4000,
			4400,
			4000,
			4000,
			5000,
			6000,
			5000,
			5600,
			5000,
			8000,
			0, //'Executor-class Star Destroyer',
			600,
			800,
			800,
			800,
			800,
			5200,
			5200,
			5200,
			5200,
			5200,
			5200,
			5200,
			5200,
			5200,
			5200,
			500,
			500,
			0, //'Unused',
			0, //'Unused',
			0, //'Unused',
			20,
			20,
			20,
			40,
			0, //'Unused',
			500,
			500,
			0, //'Unused',
			500,
			500,
			0, //'Unused',
			0, //'Asteroid Field',
			0, //'Planet',
			0, //'Unused',
			0, //'Unused',
			0, //'Shipyard',
			0, //'Repair Yard',
			0, //'Modified Strike Cruiser'
		);
		return isset($points[$this->ID]) ? $points[$this->ID] : 0;
	}
} 