<?php
namespace Pyrite\TIE;

class Constants {

	public static $CRAFTTYPE = [
		0 => "None",
		1 => "X-wing",
		2 => "Y-wing",
		3 => "A-wing",
		4 => "B-wing",
		5 => "TIE Fighter",
		6 => "TIE Interceptor",
		7 => "TIE Bomber",
		8 => "TIE Advanced",
		9 => "TIE Defender",
		10 => "Unused",
		11 => "Unused",
		12 => "Missile Boat",
		13 => "T-wing",
		14 => "Z-95 Headhunter",
		15 => "R-41 Starchaser",
		16 => "Assault Gunboat",
		17 => "Shuttle",
		18 => "Escort Shuttle",
		19 => "System Patrol Craft",
		20 => "Scout Craft",
		21 => "Stormtrooper Transport",
		22 => "Assault Transport",
		23 => "Escort Transport",
		24 => "Tug",
		25 => "Combat Utility Vehicle",
		26 => "Container A",
		27 => "Container B",
		28 => "Container C",
		29 => "Container D",
		30 => "Heavy Lifter",
		31 => "Unused",
		32 => "Bulk Freighter",
		33 => "Cargo Ferry",
		34 => "Modular Conveyor",
		35 => "Container Transport",
		36 => "Unused",
		37 => "Murrian Transport",
		38 => "Corellian Transport",
		39 => "Unused",
		40 => "Corellian Corvette",
		41 => "Modified Corvette",
		42 => "Nebulon-B Frigate",
		43 => "Modified Frigate",
		44 => "C-3 Passenger Liner",
		45 => "Carrack Cruiser",
		46 => "Strike Cruiser",
		47 => "Escort Carrier",
		48 => "Dreadnaught",
		49 => "Mon Calamari Cruiser",
		50 => "Light Mon Calamari Cruiser",
		51 => "Interdictor Cruiser",
		52 => "Victory-class Star Destroyer",
		53 => "Imperator-class Star Destroyer",
		54 => "Unused",
		55 => "Container E",
		56 => "Container F",
		57 => "Container G",
		58 => "Container H",
		59 => "Container I",
		60 => "Platform A",
		61 => "Platform B",
		62 => "Platform C",
		63 => "Platform D",
		64 => "Platform E",
		65 => "Platform F",
		66 => "Asteroid R&D Station",
		67 => "Asteroid Laser Battery",
		68 => "Asteroid Warhead Battery",
		69 => "X/7 Factory",
		70 => "Satellite 1",
		71 => "Satellite 2",
		72 => "Unused",
		73 => "Unused",
		74 => "Unused",
		75 => "Mine A",
		76 => "Mine B",
		77 => "Mine C",
		78 => "Unused",
		79 => "Unused",
		80 => "Probe A",
		81 => "Probe B",
		82 => "Unused",
		83 => "Nav Buoy A",
		84 => "Nav Buoy B",
		85 => "Unused",
		86 => "Asteroid Field",
		87 => "Planet",
	];

	public static $STATUS = [
		0 => "None",
		1 => "2X Warheads",
		2 => "1/2 Warheads",
		3 => "Disabled",
		4 => "1/2 Shields",
		5 => "No Lasers",
		6 => "No Hyperdrive",
		7 => "Shields 0%, charging",
		8 => "Shields added or 200%",
		9 => "Hyperdrive added",
		20 => "Invincible",
	];

	public static $WARHEAD = [
		0 => "None",
		1 => "Heavy Rocket",
		2 => "Space Bomb",
		3 => "Concussion Missile",
		4 => "Torpedo",
		5 => "Advanced Concussion Missile",
		6 => "Advanced Torpedo",
		7 => "Mag Pulse Torpedo",
	];

	public static $BEAM = [
		0 => "None",
		1 => "Tractor Beam",
		2 => "Jamming Beam",
	];

	public static $GROUPAI = [
		0 => "Rookie (None)",
		1 => "Novice",
		2 => "Veteran",
		3 => "Officer",
		4 => "Ace",
		5 => "Top Ace (Invincible)",
	];

	public static $MARKINGS = [
		0 => "Red (TIE - None)",
		1 => "Gold (TIE - Red)",
		2 => "Blue (TIE - Gold)",
		3 => "Green (TIE - Blue)",
	];

	public static $FORMATION = [
		0 => "Vic",
		1 => "Finger Four",
		2 => "Line Astern",
		3 => "Line Abreast",
		4 => "Echelon Right",
		5 => "Echelon Left",
		6 => "Double Astern",
		7 => "Diamond",
		8 => "Stack",
		9 => "High X",
		10 => "Vic Abreast",
		11 => "High Vic",
		12 => "Reverse High Vic",
	];

	public static $ARRIVALDIFFICULTY = [
		0 => "All",
		1 => "Easy",
		2 => "Medium",
		3 => "Hard",
		4 => "Medium, Hard",
		5 => "Easy, Medium",
	];

	public static $CONDITION = [
		0 => "Always (true)",
		1 => "Created",
		2 => "Destroyed",
		3 => "Attacked",
		4 => "Captured",
		5 => "Inspected",
		6 => "Boarded",
		7 => "Docked",
		8 => "Disabled",
		9 => "Survived (exist)",
		10 => "None (false)",
		11 => "Unknown (---)",
		12 => "Completed mission",
		13 => "Completed Primary Goals",
		14 => "Failed Primary Goals",
		15 => "Completed Secondary Goals",
		16 => "Failed Secondary Goals",
		17 => "Completed Bonus Goals",
		18 => "Failed Bonus Goals",
		19 => "Dropped off",
		20 => "Reinforced",
		21 => "0% Shields",
		22 => "50% Hull",
		23 => "Out of Warheads",
		24 => "Unknown (arrive?)",
	];

	public static $VARIABLETYPE = [
		0 => "None",
		1 => "Flight Group",
		2 => "CraftType (enum)",
		3 => "CraftCategory (enum)",
		4 => "ObjectCategory (enum)",
		5 => "IFF",
		6 => "Order (enum)",
		7 => "CraftWhen (enum)",
		8 => "Global Group",
		9 => "Misc (enum)",
		10 => "Unknown",
	];

	public static $CRAFTCATEGORY = [
		0 => "Starfighters",
		1 => "Transports",
		2 => "Freighters/Containers",
		3 => "Starships",
		4 => "Utility Craft",
		5 => "Platforms/Facilities",
		6 => "Mines",
	];

	public static $OBJECTCATEGORY = [
		0 => "Craft",
		1 => "Weapons",
		2 => "Space Objects",
	];

	public static $TRIGGERAMOUNT = [
		0 => "100%",
		1 => "75%",
		2 => "50%",
		3 => "25%",
		4 => "At least one",
		5 => "All but one",
		6 => "Special craft",
		7 => "All non-special craft",
		8 => "All non-player craft",
		9 => "Player's craft",
		10 => "100% of first wave",
		11 => "75% of first wave",
		12 => "50% of first wave",
		13 => "25% of first wave",
		14 => "At least one of first wave",
		15 => "All but one of first wave",
	];

	public static $GOALAMOUNT = [
		0 => "100%",
		1 => "50%",
		2 => "At least one",
		3 => "All but one",
		4 => "Special craft",
	];

	public static $ABORTTRIGGER = [
		0 => "None",
		1 => "0% Shields",
		2 => "Systems 75% (fighters and transports only)",
		3 => "Out of warheads",
		4 => "50% Hull",
		5 => "Attacked",
	];

	public static $ORDER = [
		0 => "Hold Station",
		1 => "Go Home",
		2 => "Circle",
		// Var1 Docking Time (seconds x 5)
		3 => "Circle and Evade",
		4 => "Rendezvous",
		5 => "Disabled",
		6 => "Await Boarding",
		7 => "Attack",
		8 => "Attack Escorts",
		9 => "Protect",
		10 => "Escort",
		11 => "Disable",
		12 => "Board and Give Cargo",
		// Var2 Number of Dockings
		13 => "Board and Take Cargo",
		14 => "Board and Exchange Cargo",
		15 => "Board and Capture Cargo",
		16 => "Board and Destroy Cargo",
		17 => "Pick up",
		18 => "Drop off",
		19 => "Wait",
		20 => "SS Wait",
		21 => "SS Patrol Loop",
		22 => "SS Await Return",
		23 => "SS Launch",
		24 => "SS Protect",
		25 => "SS Wait and Protect",
		26 => "SS Patrol and Attack",
		27 => "SS Patrol and Disable",
		28 => "SS Hold Steady",
		29 => "SS Go Home",
		30 => "SS Wait",
		31 => "SS Board",
		32 => "Board to Repair",
		33 => "Hold Station",
		34 => "Hold Steady",
		35 => "SS Hold Station",
		36 => "SS Kamikaze?",
		37 => "SS Kamikaze?",
		38 => "SS Disabled",
		39 => "SS Disabled",
	];

	public static $CRAFTWHEN = [
		1 => "Boarding",
		2 => "Boarded",
		3 => "Defence",
		4 => "Disabled",
		7 => "Special craft",
		8 => "Non-special craft",
		9 => "Player's craft",
		10 => "Non-player's craft",
	];

	public static $MISC = [
		0 => "Rookie craft",
		1 => "Novice craft",
		2 => "Officer craft",
		3 => "Veteran craft",
		4 => "Ace craft",
		5 => "Top Ace craft",
		6 => "Stationary craft",
		7 => "Craft returning to base",
		8 => "Non-evading craft",
		9 => "Craft in formation",
		10 => "Rendezvousing craft",
		11 => "Disabled craft",
		12 => "Craft awaiting boarding",
		13 => "Attacking craft",
		14 => "Craft atatcking escorts",
		15 => "Protecting craft",
		16 => "Escorting craft",
		17 => "Disabling craft",
		18 => "Delivering craft",
		19 => "Siezing craft",
		20 => "Exchanging craft",
		21 => "Capturing craft",
		22 => "Craft destroying cargo",
		23 => "Picked up craft",
		24 => "Dropped off craft",
		25 => "Waiting fighters",
		26 => "Waiting starships",
		27 => "Patrolling starships",
		28 => "SS awaiting returns",
		29 => "SS waiting to launch",
		30 => "SS waiting to be boarded",
		31 => "SS witing for boarding craft to appear",
		32 => "SS attacking",
		33 => "SS disabling",
		34 => "SS disabling?",
		35 => "SS flying home",
		36 => "Rebels",
		37 => "Imperials",
		39 => "Spacecraft",
		40 => "Weapons",
		41 => "Space objects",
		46 => "Fighters",
		47 => "Transports",
		48 => "Freighters",
		49 => "Utility craft",
		50 => "Startships",
		51 => "Platforms",
		54 => "Mines",
	];

	public static $EVENTTYPE = [
		3 => "Page Break",
		4 => "Title Text",
		// Var1 Tag#
		5 => "Caption Text",
		6 => "Move Map",
		// Var2 TextTagColor (enum)
		7 => "Zoom Map",
		8 => "Clear FG Tags",
		9 => "FG Tag 1",
		10 => "FG Tag 2",
		11 => "FG Tag 3",
		12 => "FG Tag 4",
		13 => "FG Tag 5",
		14 => "FG Tag 6",
		15 => "FG Tag 7",
		16 => "FG Tag 8",
		17 => "Clear Text Tags",
		18 => "Text Tag 1",
		// Var3 X
		// Var4 Y
		19 => "Text Tag 2",
		20 => "Text Tag 3",
		21 => "Text Tag 4",
		22 => "Text Tag 5",
		23 => "Text Tag 6",
		24 => "Text Tag 7",
		25 => "Text Tag 8",
		34 => "End Briefing",
	];

	public static $TEXTTAGCOLOR = [
		0 => "Green",
		1 => "Red",
		2 => "Purple",
		3 => "Blue",
		4 => "Red",
		5 => "Light Red",
		6 => "Gray",
		7 => "White",
	];

	public static $BRIEFINGOFFICERS = [
		1 => "Both officers",
		2 => "Flight Officer",
		3 => "Secret Order",
	];

	public static $QUESTIONTYPE = [
		0 => "None",
		1 => "Primary Goals",
		2 => "Secondary Goals",
	];

	public static $QUESTIONCONDITION = [
		0 => "None",
		4 => "Successful",
		5 => "Failed",
	];

	public static $MESSAGECOLOR = [
		0 => "Red",
		1 => "Green",
		2 => "Blue",
		3 => "Purple",
	];
}